name: Test

on:
  push: null
  pull_request: null
  schedule: 
    - cron: '0 12 * * *'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        rust:
          - stable
          - nightly
        features:
          - ""
          - --no-default-features
        include:
          - rust: nightly
            cargo_flags: -Z minimal-versions

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            target
          key: ${{ matrix.os }}-${{ matrix.rust }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.rust }}-
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Build
        run:
          cargo build ${{ matrix.features }} ${{ matrix.cargo_flags }}
      - name: Test
        run:
          cargo test ${{ matrix.features }} --all-targets --no-fail-fast --workspace
      - name: Test with macro
        run:
          cargo test --manifest-path examples/macro/Cargo.toml
      - name: Test without macro
        run:
          cargo test --manifest-path examples/no_macro/Cargo.toml
      - name: Doc Test
        run:
          cargo test --all-features --doc --no-fail-fast --workspace
      - name: Build Docs
        run:
          cargo doc ${{ matrix.features }} --workspace --no-deps
